name: ci
on: [push, pull_request]
jobs:
  build-backend-17:
    runs-on: ubuntu-latest
    env:
      working-directory: ./java17
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: verify
        run: mvn -B verify
        working-directory: ${{env.working-directory}}
  build-backend-11:
    runs-on: ubuntu-latest
    env:
      working-directory: ./java11
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: verify
        run: mvn -B verify
        working-directory: ${{env.working-directory}}
